# Generated by Django 3.1 on 2020-11-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201106_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student_abroad', 'Студент за рубежом'), ('university_employee', 'Сотрудник университета'), ('student_applicant', 'Кандидат на отбор в конкурсе')], default='super_user', max_length=255, verbose_name='Тип пользователя'),
        ),
    ]
