# Generated by Django 3.1 on 2020-08-13 06:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20200813_1117'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.customuser')),
                ('lastname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=200, verbose_name='Имя')),
                ('fathersname', models.CharField(blank=True, max_length=200, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения')),
                ('gender', models.CharField(default='Мужской', max_length=10, verbose_name='Пол')),
                ('last_edu', models.CharField(max_length=70, verbose_name='Последнее место обучения')),
                ('last_education_place', models.CharField(blank=True, max_length=220, verbose_name='Название предыдущего учебного заведения')),
                ('education_country', models.CharField(max_length=200, verbose_name='Страна обучения')),
                ('university_name', models.CharField(max_length=200, verbose_name='Название учебного заведения')),
                ('year_of_applying', models.DateField(default=django.utils.timezone.now, verbose_name='Год поступления')),
                ('education_program', models.CharField(max_length=200, verbose_name='Программа обучения')),
                ('education_period', models.CharField(max_length=200, verbose_name='Период обучения')),
                ('speciality', models.CharField(max_length=200, verbose_name='Специальность')),
                ('education_form', models.CharField(default='Контракт', max_length=20, verbose_name='Форма обучения')),
                ('status', models.CharField(default='Зачислен', max_length=200, verbose_name='Статус студента')),
                ('phone_number', models.CharField(max_length=200, unique=True, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=200, unique=True, verbose_name='E-mail')),
                ('parent_name', models.CharField(max_length=200, verbose_name='ФИО родственника')),
                ('parent_type', models.CharField(max_length=200, verbose_name='Степень родства')),
                ('parent_phone_number', models.CharField(max_length=200, verbose_name='Телефонные номера')),
                ('parent_second_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО второго родственника')),
                ('parent_second_type', models.CharField(blank=True, max_length=200, verbose_name='Степень родства')),
                ('parent_second_phone_number', models.CharField(blank=True, max_length=200, verbose_name='Телефонные номера')),
                ('last_university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='universities.university')),
            ],
            options={
                'ordering': ['lastname', 'firstname', 'fathersname'],
            },
        ),
    ]
