# Generated by Django 3.1 on 2020-08-13 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200813_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='last_university',
            new_name='university',
        ),
    ]
