# Generated by Django 3.1 on 2020-08-20 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200813_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='last_edu',
        ),
    ]
