# Generated by Django 3.1 on 2020-08-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_last_edu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='education_country',
            field=models.CharField(max_length=255, verbose_name='Страна обучения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='education_period',
            field=models.CharField(max_length=255, verbose_name='Период обучения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='education_program',
            field=models.CharField(max_length=255, verbose_name='Программа обучения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=255, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fathersname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_education_place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название предыдущего учебного заведения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_name',
            field=models.CharField(max_length=255, verbose_name='ФИО родственника'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone_number',
            field=models.CharField(max_length=255, verbose_name='Телефонные номера'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_second_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО второго родственника'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_second_phone_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Телефонные номера'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_second_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Степень родства'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_type',
            field=models.CharField(max_length=255, verbose_name='Степень родства'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='student',
            name='speciality',
            field=models.CharField(max_length=255, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(default='Зачислен', max_length=255, verbose_name='Статус студента'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university_name',
            field=models.CharField(max_length=255, verbose_name='Название учебного заведения'),
        ),
    ]
