# Generated by Django 3.1 on 2020-08-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200824_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='last_education_place',
            new_name='last_school',
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_second_name',
            field=models.CharField(max_length=255, verbose_name='ФИО второго родственника'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_second_phone_number',
            field=models.CharField(max_length=255, verbose_name='Телефонные номера'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_second_type',
            field=models.CharField(max_length=255, verbose_name='Степень родства'),
        ),
    ]
