# Generated by Django 3.1 on 2020-09-01 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20200830_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='students/profile_photos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='education_country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='education_form',
            field=models.CharField(default='Контракт', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='education_period',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='education_program',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='fathersname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(default='Мужской', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_school',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_second_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_second_phone_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_second_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='speciality',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(default='Зачислен', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='university_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_applying',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
