# Generated by Django 3.1 on 2020-09-02 08:09

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20200901_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='students/student_documents/')),
                ('document_file_created_at', models.DateTimeField(auto_now_add=True)),
                ('document_file_updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.constraints.CheckConstraint, to='students.student')),
            ],
        ),
    ]
