# Generated by Django 3.1 on 2020-09-02 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_documents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_documents',
            new_name='StudentDocuments',
        ),
    ]
