# Generated by Django 3.1 on 2020-09-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_studentdocuments_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='type_of_applying',
            field=models.CharField(default='по линии межвузовских Соглашений', max_length=255),
        ),
    ]
