# Generated by Django 3.1 on 2020-09-15 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_student_type_of_applying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocuments',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
