# Generated by Django 3.1 on 2020-11-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201112_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='country',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, verbose_name='Долгота'),
        ),
    ]
