# Generated by Django 3.1 on 2020-11-08 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcement', '0002_announcementdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementApplicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Участник конкурса'), ('at_registration', 'Дополнительные документы не загружены'), ('inactive', 'Регистрация не завершена')], default='inactive', max_length=255, verbose_name='Статус кандидата')),
                ('account_created_at', models.DateTimeField(auto_now_add=True)),
                ('account_updated_at', models.DateTimeField(auto_now=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
