# Generated by Django 3.1 on 2020-11-06 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edu_organisation', '0001_initial'),
        ('users', '0003_auto_20201106_1845'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplicant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.customuser')),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('fathersname', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField()),
                ('pin_code', models.CharField(max_length=255)),
                ('other', models.BooleanField(default=False)),
                ('edu_organisation_other', models.CharField(blank=True, max_length=255)),
                ('graduation_date', models.DateField()),
                ('foreign_language_level', models.CharField(max_length=255)),
                ('foreign_language_level_document', models.FileField(upload_to='student_applicant/documents/foreign_lang_level')),
                ('average_mark', models.FloatField(max_length=4)),
                ('average_mark_document', models.FileField(upload_to='student_applicant/documents/average_mark')),
                ('family_members', models.CharField(max_length=255)),
                ('family_members_document', models.FileField(upload_to='student_applicant/documents/family_member')),
                ('address', models.CharField(max_length=255)),
                ('phone_number1', models.CharField(max_length=255)),
                ('phone_number2', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('profile_photo', models.ImageField(blank=True, upload_to='student_applicant/profile_photos/')),
                ('citizenship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('edu_organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_organisation.eduorganisation')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gender')),
            ],
            options={
                'ordering': ['lastname', 'firstname', 'fathersname'],
            },
        ),
        migrations.CreateModel(
            name='StudentApplicantParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('fathersname', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('parent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parenttype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_applicant.studentapplicant')),
            ],
        ),
        migrations.CreateModel(
            name='StudentApplicantDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='student_applicant/additional_documents/')),
                ('document_file_created_at', models.DateTimeField(auto_now_add=True)),
                ('document_file_updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_applicant.studentapplicant')),
            ],
        ),
    ]
