# Generated by Django 3.1 on 2020-10-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=255, verbose_name='Название учебного заведения')),
                ('university_address', models.CharField(max_length=255, verbose_name='Фактический адрес учебного заведения')),
            ],
        ),
    ]
