# Generated by Django 3.1 on 2020-10-29 14:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('university_local', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAbroad',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.customuser')),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('fathersname', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField()),
                ('college', models.CharField(blank=True, max_length=255)),
                ('school', models.CharField(blank=True, max_length=255)),
                ('university_name', models.CharField(max_length=255)),
                ('year_of_applying', models.DateField(default=django.utils.timezone.now)),
                ('education_period_years', models.IntegerField()),
                ('education_period_months', models.IntegerField()),
                ('speciality', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('profile_photo', models.ImageField(blank=True, upload_to='student_abroad/profile_photos/')),
                ('education_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('education_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.educationform')),
                ('education_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.educationprogram')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gender')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status')),
                ('type_of_applying', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typeofapplying')),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university_local.university')),
            ],
            options={
                'ordering': ['lastname', 'firstname', 'fathersname'],
            },
        ),
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('fathersname', models.CharField(blank=True, max_length=255)),
                ('parent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_abroad.studentabroad')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parenttype')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_abroad.studentabroad')),
            ],
        ),
        migrations.CreateModel(
            name='StudentParentPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_abroad.studentparent')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='student_abroad/student_documents/')),
                ('document_file_created_at', models.DateTimeField(auto_now_add=True)),
                ('document_file_updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_abroad.studentabroad')),
            ],
        ),
    ]
