# Generated by Django 3.1 on 2020-11-02 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_abroad', '0002_auto_20201030_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentabroad',
            name='education_period_months',
        ),
    ]
