# Generated by Django 3.1 on 2020-10-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_in_kg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBulkUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('xls_file', models.FileField(upload_to='students/bulkupload/')),
            ],
        ),
    ]
