# Generated by Django 3.1 on 2020-10-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_in_kg', '0003_delete_studentbulkupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_abroad',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
