# Generated by Django 3.1 on 2020-10-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_universitybulkupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniversityBulkUpload',
        ),
    ]
